# Generated by Django 5.0.6 on 2025-10-20 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('form_fields', models.JSONField(default=list)),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', max_length=10)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('original_photo', models.ImageField(upload_to='original_photos/')),
                ('processed_photo', models.ImageField(blank=True, null=True, upload_to='processed_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.formtemplate')),
            ],
        ),
    ]
