# Generated by Django 5.0.6 on 2025-10-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='client_logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/'),
        ),
    ]
