# Generated by Django 5.0.6 on 2025-10-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_formtemplate_client_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='background_type',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='processed_photo',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_id',
        ),
    ]
