# Generated by Django 5.0.6 on 2025-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_formtemplate_background_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubmission',
            options={'ordering': ['submitted_at']},
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together={('form_template', 'unique_id')},
        ),
    ]
